// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lirlkmbrsioalqttztjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcmxrbWJyc2lvYWxxdHR6dGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTEyNTAsImV4cCI6MjA1NjU4NzI1MH0.q9WK9pQQlL_c0YN3Obe5wzYqeKkDL7u8Enl9x5OIF_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);